/* Question bank: first option in `o` is always the correct answer (options are shuffled at runtime). */
var PLACES = [
  { id:'vf', name:'Victoria Falls', lon:25.86, lat:-17.93, link:'/victoria-falls/', linkLabel:'Explore Victoria Falls', src:'https://en.wikipedia.org/wiki/Victoria_Falls',
    blurb:'Mosi-oa-Tunya — the thundering curtain of the Zambezi.',
    qs:[
      {q:'The local name for Victoria Falls, Mosi-oa-Tunya, means…', o:['The Smoke that Thunders','The River of the Gods','The Great White Water','The Place of Rainbows'], f:'The spray can rise over 400 m into the air.'},
      {q:'Which river plunges over Victoria Falls?', o:['Zambezi','Limpopo','Save','Runde'], f:'The Zambezi is Africa’s fourth-longest river.'},
      {q:'Which country shares Victoria Falls with Zimbabwe?', o:['Zambia','Botswana','Mozambique','Namibia'], f:'The border runs along the Zambezi, right through the falls.'},
      {q:'Which Scottish explorer named the falls in 1855?', o:['David Livingstone','Mungo Park','Henry Morton Stanley','Frederick Selous'], f:'He named them after Queen Victoria.'},
      {q:'Victoria Falls became a UNESCO World Heritage Site in…', o:['1989','1972','1995','2003'], f:'It is listed jointly by Zimbabwe and Zambia.'},
      {q:'Roughly how wide is the curtain of falling water?', o:['About 1.7 km','About 300 m','About 5 km','About 12 km'], f:'That makes it one of the largest sheets of falling water on Earth.'},
      {q:'Which thrill is famously done off the Victoria Falls Bridge?', o:['Bungee jumping','Skydiving','Cave diving','Paragliding'], f:'The bungee drop is 111 m towards the Zambezi.', s:'https://en.wikipedia.org/wiki/Victoria_Falls_Bridge'},
      {q:'On full-moon nights at the falls you can sometimes see a…', o:['Lunar rainbow','Meteor shower','Green flash','Double sunset'], f:'The “moonbow” forms when moonlight shines through the spray.'},
      {q:'The Victoria Falls Bridge was completed in…', o:['1905','1890','1935','1960'], f:'It spans the gorge below the falls, linking Zimbabwe and Zambia.', s:'https://en.wikipedia.org/wiki/Victoria_Falls_Bridge'},
      {q:'Victoria Falls plunges into a zigzag of gorges known as the…', o:['Batoka Gorge','Chilojo Gorge','Pungwe Gorge','Kariba Gorge'], f:'The gorges trace older positions of the falls as they cut back upstream.'},
      {q:'Victoria Falls town is in which province?', o:['Matabeleland North','Manicaland','Masvingo','Midlands'], f:'It sits at Zimbabwe\'s north-western tip.'},
      {q:'At its highest point, roughly how far does the water fall?', o:['About 100 m','About 20 m','About 400 m','About 1 km'], f:'The deepest drop is around 108 m.'},
      {q:'From which island did Livingstone first see the falls?', o:['Livingstone Island','Robben Island','Kariba Island','Big Tree Island'], f:'The island sits right on the lip of the falls.'},
      {q:'Which rock pool lets daring swimmers sit right on the edge of the falls in the dry season?', o:['Devil\'s Pool','Mermaid Pool','Tessa\'s Pool','Blue Lagoon'], f:'It is on the Zambian side, reached from Livingstone Island.'},
      {q:'The Zambian town beside the falls is named after…', o:['David Livingstone','Queen Victoria','Cecil Rhodes','Kenneth Kaunda'], f:'Livingstone was once the capital of Northern Rhodesia.'},
      {q:'When does the Zambezi usually pour over the falls at its fullest?', o:['Around March to May','Around September to November','Around June to August','Around December'], f:'Rain from upstream takes months to reach the falls.'}
    ]},
  { id:'hw', name:'Hwange', lon:26.6, lat:-19.2, link:'/hwange/', linkLabel:'Explore Hwange', src:'https://en.wikipedia.org/wiki/Hwange_National_Park',
    blurb:'Big skies, Kalahari sand and a whole lot of elephants.',
    qs:[
      {q:'Hwange is Zimbabwe’s ___ national park.', o:['Largest','Smallest','Highest','Newest'], f:'It covers roughly 14,600 km² — bigger than some countries.'},
      {q:'Hwange is especially famous for its huge herds of…', o:['Elephants','Giraffes','Zebras','Rhinos'], f:'Tens of thousands of elephants roam the park.'},
      {q:'Before 1982, Hwange was known as…', o:['Wankie','Salisbury','Fort Victoria','Umtali'], f:'Many towns were renamed in the years after independence.'},
      {q:'Hwange town is best known for mining…', o:['Coal','Gold','Diamonds','Platinum'], f:'Its coal feeds the nearby Hwange Power Station.'},
      {q:'Which famous Hwange lion, studied by researchers, made world headlines in 2015?', o:['Cecil','Simba','Mufasa','Elsa'], f:'He wore a research collar from Oxford University’s WildCRU team.', s:'https://en.wikipedia.org/wiki/Cecil_(lion)'},
      {q:'Hwange sits on the edge of which desert’s sands?', o:['Kalahari','Namib','Sahara','Gobi'], f:'Deep Kalahari sands mean very little surface water.'},
      {q:'In the dry season, many Hwange waterholes are kept full by…', o:['Pumped boreholes','Snowmelt','Canals from Lake Kariba','Monsoon rains'], f:'Without pumping, many animals would struggle to find water.'},
      {q:'Hwange National Park is in which province?', o:['Matabeleland North','Masvingo','Mashonaland West','Manicaland'], f:'It sits in the far west, near the Botswana border.'},
      {q:'Hwange was first set aside as a game reserve in…', o:['1928','1890','1960','1985'], f:'It began as the Wankie Game Reserve.'},
      {q:'Which handsome antelope with a glossy black coat and curved horns is a Hwange speciality?', o:['Sable antelope','Springbok','Gemsbok','Bongo'], f:'Males are almost jet black with a white belly.'},
      {q:'Hwange National Park borders which country?', o:['Botswana','Zambia','Mozambique','Namibia'], f:'Animals move freely across the western boundary.'},
      {q:'Which tree, with butterfly-shaped leaves, covers large parts of Hwange?', o:['Mopane','Jacaranda','Msasa','Eucalyptus'], f:'Elephants love to browse on its leaves.'},
      {q:'Painted Dog Conservation, near Hwange at Dete, protects which animal?', o:['African wild dogs','Cheetahs','Pangolins','Rhinos'], f:'The centre runs anti-poaching patrols and a rehabilitation facility.'},
      {q:'When is game viewing usually best in Hwange?', o:['In the dry season','In the rainy season','Only at Christmas','Only at night'], f:'Animals gather around the few waterholes as the bush dries out.'},
      {q:'Hwange lies roughly between Bulawayo and…', o:['Victoria Falls','Mutare','Masvingo','Kariba'], f:'The main road and railway to the falls run past the park.'}
    ]},
  { id:'kb', name:'Lake Kariba', lon:27.95, lat:-17.15, link:'/kariba/', linkLabel:'Explore Kariba', src:'https://en.wikipedia.org/wiki/Lake_Kariba',
    blurb:'A vast inland sea, sunsets and the home of Nyami Nyami.',
    qs:[
      {q:'Kariba Dam was built across which river?', o:['Zambezi','Save','Limpopo','Pungwe'], f:'The lake stretches about 220 km along the river.', s:'https://en.wikipedia.org/wiki/Kariba_Dam'},
      {q:'In which year was the Kariba Dam wall completed?', o:['1959','1935','1974','1990'], f:'By volume, Kariba became the world’s largest man-made lake.', s:'https://en.wikipedia.org/wiki/Kariba_Dam'},
      {q:'The river god said to live in the Zambezi at Kariba is…', o:['Nyami Nyami','Tokoloshe','Chipembere','Mbira'], f:'Tonga legend describes him with a snake’s body and a fish’s head.'},
      {q:'The rescue of animals stranded by the rising lake was called…', o:['Operation Noah','Operation Ark Royal','Operation Jonah','Operation Rhino'], f:'About 6,000 animals were rescued between 1958 and 1964.'},
      {q:'Which small sardine-like fish is caught at night on Kariba using lights?', o:['Kapenta','Tilapia','Tigerfish','Catfish'], f:'Kapenta rigs use bright lamps to draw the fish after dark.'},
      {q:'Kariba’s famous international fishing tournament targets which fish?', o:['Tigerfish','Kapenta','Trout','Bass'], f:'Tigerfish are known for their sharp, interlocking teeth.'},
      {q:'Which community was moved from the Zambezi Valley when the lake was created?', o:['The Tonga people','The Ndebele people','The Shangaan people','The Manyika people'], f:'Around 57,000 Tonga people were resettled.'},
      {q:'The Kariba Dam is shared between Zimbabwe and…', o:['Zambia','Mozambique','Malawi','Botswana'], f:'Each country runs a power station on its own bank.', s:'https://en.wikipedia.org/wiki/Kariba_Dam'},
      {q:'Lake Kariba is the world\'s largest man-made lake by…', o:['Volume','Surface area','Depth','Age'], f:'Ghana\'s Lake Volta covers more area, but Kariba holds more water.'},
      {q:'The Kariba Dam wall is what kind of dam?', o:['A concrete arch dam','An earth embankment','A timber dam','A rock-fill dam'], f:'Its curved wall pushes the water\'s weight into the gorge sides.'},
      {q:'Which national park lies on Lake Kariba\'s southern shore?', o:['Matusadona','Gonarezhou','Nyanga','Chimanimani'], f:'Its name comes from the Matusadona Hills behind it.'},
      {q:'A classic way to holiday on Lake Kariba is on a…', o:['Houseboat','Cable car','Steam train','Hot-air balloon'], f:'Many families spend long weekends drifting and fishing.'},
      {q:'What are the dead trees standing in Lake Kariba?', o:['Trees drowned when the valley flooded','Trees planted for fish','Old telegraph poles','Fossilised reeds'], f:'Their bare trunks still stand decades after the lake filled.'},
      {q:'Whose haunting cry is the classic sound of Lake Kariba?', o:['The African fish eagle','The hadeda ibis','The crowned crane','The ground hornbill'], f:'It swoops down to snatch fish from the water.'},
      {q:'Kariba town is in which province?', o:['Mashonaland West','Matabeleland North','Masvingo','Manicaland'], f:'It sits on hills above the dam wall.'}
    ]},
  { id:'mp', name:'Mana Pools', lon:29.35, lat:-15.8, link:'/listings/parks/', linkLabel:'Browse national parks', src:'https://en.wikipedia.org/wiki/Mana_Pools_National_Park',
    blurb:'Wild Zambezi floodplains, canoes and elephants on tiptoe.',
    qs:[
      {q:'Mana Pools became a UNESCO World Heritage Site in…', o:['1984','1960','1999','2012'], f:'It was listed together with the neighbouring Sapi and Chewore areas.'},
      {q:'In Shona, \u201cMana\u201d means…', o:['Four','Water','Elephant','Island'], f:'It refers to the four main pools left behind by the Zambezi.'},
      {q:'Mana Pools lies along which river?', o:['Zambezi','Save','Limpopo','Runde'], f:'The pools are old channels the river left behind as it shifted north.'},
      {q:'Mana\u2019s elephants famously stand on their hind legs to reach the pods of which tree?', o:['Albida (winterthorn)','Baobab','Mopane','Msasa'], f:'The albida sheds its leaves in the rainy season and fruits in the dry season.'},
      {q:'Which popular safari takes you along the river at Mana Pools?', o:['Canoe safaris','Cable car rides','Steam train trips','Submarine tours'], f:'Paddlers share the Zambezi with hippos and crocodiles.'},
      {q:'Mana Pools is unusual among African parks because visitors may…', o:['Walk without a guide','Feed the animals','Swim with hippos','Drive off-road anywhere'], f:'It is entirely at your own risk \u2014 the animals are truly wild.'},
      {q:'Mana Pools is in which province?', o:['Mashonaland West','Masvingo','Matabeleland South','Manicaland'], f:'It sits in the Zambezi Valley, below the escarpment.'},
      {q:'Mana Pools is famous for which predators, often seen hunting in packs?', o:['African wild dogs','Tigers','Jaguars','Snow leopards'], f:'Wild dogs are also called painted dogs for their patchy coats.'},
      {q:'Across the Zambezi from Mana Pools lies which Zambian park?', o:['Lower Zambezi National Park','South Luangwa','Kafue','Kasanka'], f:'Together they protect a long stretch of wild river.'},
      {q:'The famous Mana Pools elephant that stood tall on his hind legs was known as…', o:['Boswell','Dumbo','Jumbo','Babar'], f:'Photographers travelled from around the world to see him.'},
      {q:'Much of Mana Pools closes to visitors during…', o:['The rainy season','The dry season','School holidays','Full moon'], f:'Rain makes the valley roads impassable.'},
      {q:'Mana Pools\' main campsite on the riverbank is called…', o:['Nyamepi','Chipinda','Maleme','Main Camp'], f:'Campers often wake to elephants between the tents.'},
      {q:'Mana Pools lies below which escarpment?', o:['The Zambezi Escarpment','The Great Rift Escarpment','The Drakensberg','The Nyanga Escarpment'], f:'The escarpment walls off the valley to the south.'},
      {q:'Which animal spends its days in Mana\'s pools and grazes the floodplains at night?', o:['Hippo','Giraffe','Zebra','Warthog'], f:'Hippos can eat around 40 kg of grass in a night.'},
      {q:'Mana Pools shares its UNESCO listing with the Sapi and…', o:['Chewore','Matusadona','Chizarira','Charara'], f:'Together they cover a huge stretch of the Zambezi Valley.'}
    ]},
  { id:'hr', name:'Harare', lon:31.05, lat:-17.83, link:'/harare/', linkLabel:'Explore Harare', src:'https://en.wikipedia.org/wiki/Harare',
    blurb:'The Sunshine City — jacarandas, markets and the Kopje.',
    qs:[
      {q:'Before 1982, Harare was called…', o:['Salisbury','Umtali','Gwelo','Fort Victoria'], f:'The city was renamed in April 1982.'},
      {q:'In September and October, many Harare streets turn purple thanks to…', o:['Jacaranda trees','Flame lilies','Bougainvillea hedges','Msasa trees'], f:'The purple avenues are one of the city’s best-loved sights.'},
      {q:'Which granite hill overlooks Harare’s city centre?', o:['The Kopje','Domboshava','Ngomakurira','Mount Hampden'], f:'The area around the Kopje is one of the oldest parts of the city.'},
      {q:'Harare was founded as Fort Salisbury in…', o:['1890','1850','1923','1953'], f:'That makes the city well over a century old.'},
      {q:'HIFA, held in Harare, is a festival of…', o:['The arts','Motorsport','Farming','Film only'], f:'HIFA stands for Harare International Festival of the Arts.'},
      {q:'Zimbabwe’s largest sports stadium, in Harare, is…', o:['National Sports Stadium','Rufaro Stadium','Barbourfields Stadium','Harare Sports Club'], f:'It can hold around 60,000 people.'},
      {q:'Mbare Musika in Harare is best known as…', o:['A busy market and bus terminus','A botanical garden','A game park','A shopping mall'], f:'It is one of the busiest trading spots in the country.'},
      {q:'Roughly how high above sea level is Harare?', o:['About 1,500 m','About 200 m','About 800 m','About 3,000 m'], f:'Its altitude keeps the climate mild for most of the year.'},
      {q:'Harare\'s nickname is…', o:['The Sunshine City','The City of Kings','The Windy City','The City of Gold'], f:'Bulawayo is the City of Kings.'},
      {q:'The famous balancing rocks at Epworth, near Harare, once appeared on…', o:['Zimbabwe\'s banknotes','The national flag','Postage stamps only','The coat of arms'], f:'They are often called the Banknote Rocks.'},
      {q:'Lake Chivero, Harare\'s main water supply, was formerly called…', o:['Lake McIlwaine','Lake Kyle','Lake Kariba','Lake Victoria'], f:'It is also a popular spot for picnics and game drives.'},
      {q:'Domboshava, just north of Harare, is known for…', o:['Granite domes and rock paintings','Hot springs','Sand dunes','A cable car'], f:'Sunset from the top of the dome is a Harare favourite.'},
      {q:'Harare is Zimbabwe\'s…', o:['Capital and largest city','Second city','Oldest town','Only city'], f:'It is also the country\'s main business centre.'},
      {q:'Which national art museum is in Harare?', o:['National Gallery of Zimbabwe','Louvre Africa','Zeitz MOCAA','Iziko Gallery'], f:'It showcases Zimbabwean stone sculpture and painting.'},
      {q:'Mukuvisi Woodlands in Harare is…', o:['A nature reserve inside the city','A shopping centre','A football stadium','A railway station'], f:'You can walk among zebra and giraffe minutes from town.'}
    ]},
  { id:'ny', name:'Nyanga', lon:32.62, lat:-18.3, link:'/nyanga/', linkLabel:'Explore Nyanga', src:'https://en.wikipedia.org/wiki/Nyanga_National_Park',
    blurb:'Misty Eastern Highlands, trout streams and Zimbabwe’s rooftop.',
    qs:[
      {q:'Zimbabwe’s highest mountain, in Nyanga National Park, is…', o:['Mount Nyangani','Mount Binga','Mount Hampden','Mount Darwin'], f:'It rises to about 2,592 m.', s:'https://en.wikipedia.org/wiki/Mount_Nyangani'},
      {q:'Zimbabwe’s highest waterfall, near Nyanga, is…', o:['Mutarazi Falls','Bridal Veil Falls','Pungwe Falls','Chivirira Falls'], f:'Mutarazi drops about 762 m in two tiers.', s:'https://en.wikipedia.org/wiki/Mutarazi_Falls'},
      {q:'Nyanga is in which province?', o:['Manicaland','Masvingo','Midlands','Mashonaland Central'], f:'It is part of the Eastern Highlands, near Mozambique.'},
      {q:'The cool streams and dams of Nyanga are famous for fishing…', o:['Trout','Tigerfish','Kapenta','Catfish'], f:'Trout thrive in the highlands’ cold, clear water.'},
      {q:'Nyanga National Park was originally the private estate of…', o:['Cecil John Rhodes','David Livingstone','Frederick Selous','Charles Coghlan'], f:'He left the land to the nation in his will.'},
      {q:'Mount Nyangani is known among hikers for…', o:['Sudden mists that confuse hikers','Being an active volcano','Snow all year round','A cable car to the top'], f:'Weather on the summit can change within minutes.', s:'https://en.wikipedia.org/wiki/Mount_Nyangani'},
      {q:'Nyanga’s ancient stone-lined hollows, thought to have held livestock, are called…', o:['Pit structures','Conical towers','Rock gongs','Salt pans'], f:'They were built by farming communities several centuries ago.'},
      {q:'Which best describes the Nyanga landscape?', o:['Cool, misty highlands','Hot desert dunes','Flat salt pans','Tropical beaches'], f:'Pine forests and grassy hills make it feel a world away from the lowveld.'},
      {q:'Nyanga was previously spelt…', o:['Inyanga','Nyangani','Umtali','Melsetter'], f:'Many place names were respelt after independence.'},
      {q:'Which river\'s falls and gorge are found in Nyanga National Park?', o:['Pungwe','Zambezi','Runde','Save'], f:'The Pungwe flows on into Mozambique.'},
      {q:'Local people regard Mount Nyangani as…', o:['A sacred mountain','A volcano','A mining site','A ski slope'], f:'Visitors are asked to treat it with respect.'},
      {q:'Nyanga\'s cool highland farms are well known for growing…', o:['Apples','Bananas','Mangoes','Cocoa'], f:'Roadside stalls sell fresh fruit to passing travellers.'},
      {q:'Which thrill lets visitors walk out above Mutarazi Falls?', o:['A skywalk and zip line','A funicular railway','A bungee tower','A glass lift'], f:'The walkway hangs above the Honde Valley.'},
      {q:'Roughly how far is Nyanga from Harare by road?', o:['About 270 km','About 50 km','About 800 km','About 1,500 km'], f:'It is a popular long-weekend escape.'},
      {q:'The Rhodes Nyanga Hotel was once…', o:['Cecil Rhodes\' home','A railway station','A mission school','A military fort'], f:'Part of his old homestead now houses the Rhodes Museum.'}
    ]},
  { id:'cm', name:'Chimanimani', lon:32.9, lat:-19.8, link:'/listings/hiking-trails/', linkLabel:'Find hiking trails', src:'https://en.wikipedia.org/wiki/Chimanimani_National_Park',
    blurb:'Jagged quartzite peaks, bridal-veil waterfalls and caves to sleep in.',
    qs:[
      {q:'The Chimanimani mountains form Zimbabwe\u2019s border with…', o:['Mozambique','Zambia','Botswana','South Africa'], f:'The range continues into Mozambique\u2019s Chimanimani National Reserve.'},
      {q:'Which waterfall near Chimanimani town is named after a wedding garment?', o:['Bridal Veil Falls','Mutarazi Falls','Pungwe Falls','Victoria Falls'], f:'The water fans out over the rock like a veil.'},
      {q:'The Chimanimani mountains are mostly made of…', o:['Quartzite','Basalt','Limestone','Coal'], f:'The pale quartzite gives the peaks their bright, jagged look.'},
      {q:'Chimanimani is in which province?', o:['Manicaland','Masvingo','Midlands','Mashonaland East'], f:'It lies in the southern part of the Eastern Highlands.'},
      {q:'How do most visitors explore Chimanimani National Park?', o:['On foot','By cable car','By train','On a paved scenic road'], f:'There are no roads inside the park \u2014 it is hikers\u2019 country.'},
      {q:'Hikers in the Chimanimani mountains often spend the night in…', o:['Natural rock caves','Hotels on the peaks','Houseboats','Treehouses'], f:'Overhanging rock shelters make ready-made camps.'},
      {q:'Which 2019 cyclone caused devastating floods in Chimanimani?', o:['Cyclone Idai','Cyclone Eline','Cyclone Freddy','Cyclone Katrina'], f:'The district is still rebuilding roads and homes.', s:'https://en.wikipedia.org/wiki/Cyclone_Idai'},
      {q:'Chimanimani\u2019s highest peak, on the border, is…', o:['Mount Binga','Mount Nyangani','Mount Darwin','Mount Kilimanjaro'], f:'It is also Mozambique\u2019s highest point.'},
      {q:'Chimanimani town was formerly called…', o:['Melsetter','Umtali','Inyanga','Gwelo'], f:'It was renamed after independence.'},
      {q:'Which large antelope has a sanctuary right beside Chimanimani town?', o:['Eland','Sable','Kudu','Impala'], f:'The eland is one of Africa\'s largest antelopes.'},
      {q:'Which city is the usual gateway to Chimanimani?', o:['Mutare','Bulawayo','Gweru','Kariba'], f:'The drive heads south through the Eastern Highlands.'},
      {q:'Which natural swimming spot is found near Chimanimani village?', o:['Tessa\'s Pool','Devil\'s Pool','Mana Pool','Rhodes\' Pool'], f:'It is a favourite place to cool off after a hike.'},
      {q:'Chirinda Forest, south of Chimanimani, is home to…', o:['Zimbabwe\'s tallest tree','A cable car','An active volcano','A salt pan'], f:'The \'Big Tree\' is a red mahogany about 65 m tall.'},
      {q:'Which district borders Chimanimani to the south?', o:['Chipinge','Nyanga','Hwange','Kariba'], f:'Chipinge is known for its tea and coffee estates.'},
      {q:'Where do hikers usually enter Chimanimani National Park?', o:['Mutekeswane base camp','Main Camp','Chipinda Pools','Nyamepi'], f:'From there, a steep path climbs to the mountain hut.'}
    ]},
  { id:'gn', name:'Gonarezhou', lon:31.9, lat:-21.3, link:'/listings/parks/', linkLabel:'Browse national parks', src:'https://en.wikipedia.org/wiki/Gonarezhou_National_Park',
    blurb:'Red cliffs, big rivers and the lowveld\u2019s land of elephants.',
    qs:[
      {q:'The name Gonarezhou means…', o:['Place of elephants','Red mountain','Great river','Land of lions'], f:'Its elephants are known for being wary of people.'},
      {q:'Gonarezhou\u2019s famous red sandstone cliffs are called…', o:['Chilojo Cliffs','The Kopje','World\u2019s View','Batoka Gorge'], f:'They glow deep orange at sunset.'},
      {q:'Gonarezhou is Zimbabwe\u2019s ___ national park.', o:['Second-largest','Smallest','Highest','Newest'], f:'Only Hwange is bigger.'},
      {q:'Gonarezhou is part of the Great Limpopo Transfrontier Park, shared with Mozambique and…', o:['South Africa','Zambia','Botswana','Namibia'], f:'South Africa\u2019s Kruger National Park is part of it.', s:'https://en.wikipedia.org/wiki/Great_Limpopo_Transfrontier_Park'},
      {q:'Gonarezhou is in which province?', o:['Masvingo','Matabeleland North','Mashonaland West','Harare'], f:'It lies in the far south-east of the country.'},
      {q:'Which river flows beneath the Chilojo Cliffs?', o:['Runde','Zambezi','Gwayi','Mazowe'], f:'The cliffs tower over the wide, sandy riverbed.'},
      {q:'Which two rivers meet at a famous confluence in Gonarezhou?', o:['Save and Runde','Zambezi and Kafue','Limpopo and Shashe','Nyanga and Pungwe'], f:'Two large natural pans formed near where they meet, in the north of the park.'},
      {q:'Gonarezhou lies in which kind of landscape?', o:['Hot, dry lowveld','Cool, misty highlands','Snowy mountains','Coastal mangroves'], f:'Baobabs dot the dry, sandy plains.'},
      {q:'Gonarezhou\'s park headquarters is at…', o:['Chipinda Pools','Main Camp','Nyamepi','Maleme'], f:'It sits on the Runde River.'},
      {q:'Gonarezhou is run by ZimParks in partnership with…', o:['Frankfurt Zoological Society','WWF Japan','London Zoo','The Smithsonian'], f:'The partnership formed the Gonarezhou Conservation Trust.'},
      {q:'Which river flows through the southern part of Gonarezhou?', o:['Mwenezi','Zambezi','Pungwe','Mazowe'], f:'It joins the Limpopo further south.'},
      {q:'Roughly how big is Gonarezhou?', o:['About 5,000 km²','About 50 km²','About 50,000 km²','About 500 km²'], f:'That\'s roughly a third the size of Hwange.'},
      {q:'Across the border, Gonarezhou joins Mozambique\'s…', o:['Limpopo National Park','Gorongosa','Niassa Reserve','Bazaruto'], f:'Both are part of the Great Limpopo Transfrontier Park.'},
      {q:'Which town is the main gateway to Gonarezhou?', o:['Chiredzi','Kariba','Nyanga','Hwange'], f:'Most visitors pass through it on the way into the park.'},
      {q:'The lowveld around Gonarezhou is famous for growing…', o:['Sugar cane','Tea','Apples','Wheat'], f:'Estates at Triangle and Hippo Valley stretch for miles.'}
    ]},
  { id:'gz', name:'Great Zimbabwe', lon:30.93, lat:-20.27, link:'/great-zimbabwe-masvingo/', linkLabel:'Explore Great Zimbabwe & Masvingo', src:'https://en.wikipedia.org/wiki/Great_Zimbabwe',
    blurb:'The houses of stone that gave the country its name.',
    qs:[
      {q:'The name “Zimbabwe” comes from Shona words meaning…', o:['Houses of stone','Land of rivers','Great king','Place of the sun'], f:'From “dzimba dza mabwe”.'},
      {q:'Great Zimbabwe lies near which town?', o:['Masvingo','Gweru','Kwekwe','Chinhoyi'], f:'It is about 30 km south-east of the town.'},
      {q:'The stone walls of Great Zimbabwe were built…', o:['Without mortar','With cement','From mud bricks','With iron bolts'], f:'Granite blocks were carefully stacked and fitted by hand.'},
      {q:'Great Zimbabwe flourished roughly between the…', o:['11th and 15th centuries','1st and 3rd centuries','17th and 19th centuries','6th and 8th centuries'], f:'At its peak it may have housed thousands of people.'},
      {q:'The carved soapstone birds found here now appear on…', o:['Zimbabwe’s national flag','The South African rand','The Olympic flag','The UN emblem'], f:'The Zimbabwe Bird is also on the coat of arms.'},
      {q:'The tall, solid tower inside the Great Enclosure is called…', o:['The Conical Tower','The Hill Tower','The Bird Pillar','The King’s Chimney'], f:'It is about 10 m tall and has no inner chamber.'},
      {q:'Great Zimbabwe became a UNESCO World Heritage Site in…', o:['1986','1965','1999','2010'], f:'It is one of Africa’s most important archaeological sites.'},
      {q:'Which lake lies close to Great Zimbabwe?', o:['Lake Mutirikwi','Lake Kariba','Lake Chivero','Lake Malawi'], f:'It was formerly called Lake Kyle.'},
      {q:'The oldest part of Great Zimbabwe, on the granite hill, is called the…', o:['Hill Complex','Great Enclosure','Valley Fort','King’s Kraal'], f:'It looks down over the whole valley.'},
      {q:'The largest structure at Great Zimbabwe is called the…', o:['Great Enclosure','Hill Complex','Grand Palace','Stone Circle'], f:'Its outer wall is about 250 m long.'},
      {q:'How many carved soapstone birds were found at Great Zimbabwe?', o:['Eight','Two','Twenty','One hundred'], f:'Most have now been returned home to Zimbabwe.'},
      {q:'Great Zimbabwe grew rich from trade in…', o:['Gold','Oil','Coffee','Rubber'], f:'Gold was traded towards the East African coast.'},
      {q:'Porcelain from which faraway country was found at Great Zimbabwe?', o:['China','Brazil','Norway','Mexico'], f:'It shows how far its trade network reached.'},
      {q:'The Great Enclosure\'s outer wall reaches roughly how high?', o:['About 11 m','About 2 m','About 50 m','About 100 m'], f:'It is up to around 5 m thick in places.'},
      {q:'Great Zimbabwe was built by the ancestors of which people?', o:['The Shona','The Zulu','The Maasai','The Berbers'], f:'It was once the capital of a powerful kingdom.'}
    ]},
  { id:'mt', name:'Matobo Hills', lon:28.5, lat:-20.55, link:'/bulawayo-matobo/', linkLabel:'Explore Bulawayo & Matobo', src:'https://en.wikipedia.org/wiki/Matobo_National_Park',
    blurb:'Balancing granite, ancient rock art and black eagles overhead.',
    qs:[
      {q:'The Matobo Hills are famous for…', o:['Balancing granite rocks','Active volcanoes','Sand dunes','Glaciers'], f:'The granite here is more than two billion years old.'},
      {q:'Matobo National Park is closest to which city?', o:['Bulawayo','Gweru','Masvingo','Mutare'], f:'It is about 35 km south of the city.'},
      {q:'The Matobo Hills became a UNESCO World Heritage Site in…', o:['2003','1980','1989','2015'], f:'It was listed for its rock art and living cultural traditions.'},
      {q:'The ancient paintings in Matobo’s caves were made by…', o:['San hunter-gatherers','Portuguese traders','Victorian explorers','Roman soldiers'], f:'Some of the paintings are thousands of years old.'},
      {q:'Matobo has one of the world’s densest populations of which bird of prey?', o:['Verreaux’s (black) eagle','Bald eagle','Secretary bird','Harpy eagle'], f:'The rocky hills are perfect nesting ground for them.'},
      {q:'Matobo National Park is a stronghold for which endangered animals?', o:['Rhinos','Mountain gorillas','Okapis','Bonobos'], f:'Both black and white rhinos are protected here.'},
      {q:'The name “Matobo” is said to mean…', o:['Bald heads','Singing stones','Red earth','Many rivers'], f:'King Mzilikazi is said to have named the hills after their smooth granite domes.'},
      {q:'Which Matobo hilltop is also known as “World’s View”?', o:['Malindidzimu','Nyangani','Domboshava','Ngomakurira'], f:'Its name means “dwelling place of the spirits”.'},
      {q:'Which Ndebele king is buried in the Matobo Hills?', o:['Mzilikazi','Shaka','Moshoeshoe','Cetshwayo'], f:'He founded the Ndebele kingdom in the 1800s.'},
      {q:'Which Matobo cave is famous for its rock paintings of giraffes and antelope?', o:['Nswatugi Cave','Chinhoyi Caves','Sudwala Caves','Cango Caves'], f:'Its paintings include beautifully drawn giraffes and eland.'},
      {q:'The Matobo Hills are made mostly of…', o:['Granite','Sandstone','Chalk','Basalt'], f:'Weathering has sculpted it into domes and balancing towers.'},
      {q:'Matobo became a national park in…', o:['1926','1980','1890','2003'], f:'That makes it Zimbabwe\'s oldest national park.'},
      {q:'Which dam in Matobo is a favourite spot for picnics and camping?', o:['Maleme Dam','Kariba Dam','Mazvikadei Dam','Tokwe Mukosi Dam'], f:'Chalets sit on the rocks above the water.'},
      {q:'Matobo is in which province?', o:['Matabeleland South','Mashonaland East','Manicaland','Midlands'], f:'It lies just south of Bulawayo.'},
      {q:'Which British colonialist is buried at World\'s View in Matobo?', o:['Cecil Rhodes','David Livingstone','Frederick Selous','Charles Darwin'], f:'His grave is cut into the granite summit.'}
    ]}
];
